"""
Dashboard Export Services
Generate Excel and PDF exports from dashboard data
"""

from datetime import datetime
from io import BytesIO
from typing import Any
import pandas as pd


def export_dashboard_to_excel(
    data: dict,
    company_name: str = "Siete CX",
    report_title: str = "Dashboard Report"
) -> BytesIO:
    """
    Export dashboard data to Excel format
    
    Args:
        data: Dictionary containing dashboard metrics and lists
        company_name: Company name for the report header
        report_title: Title for the report
    
    Returns:
        BytesIO buffer containing Excel file
    """
    
    output = BytesIO()
    
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        # Summary Sheet
        if 'summary' in data or any(k in data for k in [
            'total_companies', 'total_users', 'total_evaluations',
            'completed_evaluations', 'pending_evaluations', 'avg_nps'
        ]):
            summary_data = {
                'Metric': [],
                'Value': []
            }
            
            # Extract KPI metrics
            metrics_map = {
                'total_companies': 'Total Companies',
                'total_users': 'Total Users',
                'total_evaluations': 'Total Evaluations',
                'completed_evaluations': 'Completed Evaluations',
                'pending_evaluations': 'Pending Evaluations',
                'avg_nps': 'Average NPS',
                'active_campaigns': 'Active Campaigns',
            }
            
            for key, label in metrics_map.items():
                if key in data:
                    summary_data['Metric'].append(label)
                    summary_data['Value'].append(data[key])
            
            df_summary = pd.DataFrame(summary_data)
            df_summary.to_excel(writer, sheet_name='Summary', index=False)
        
        # Evaluations By Month
        if 'evaluations_by_month' in data:
            df_monthly = pd.DataFrame(data['evaluations_by_month'])
            df_monthly.to_excel(writer, sheet_name='Monthly Evaluations', index=False)
        
        # Top Evaluators
        if 'top_evaluators' in data:
            df_evaluators = pd.DataFrame(data['top_evaluators'])
            df_evaluators.to_excel(writer, sheet_name='Top Evaluators', index=False)
        
        # Companies Summary (Superadmin)
        if 'companies_summary' in data:
            df_companies = pd.DataFrame(data['companies_summary'])
            df_companies.to_excel(writer, sheet_name='Companies', index=False)
        
        # Add metadata sheet
        metadata = {
            'Report': [report_title],
            'Company': [company_name],
            'Generated': [datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
            'Generated By': ['Siete CX Platform']
        }
        df_metadata = pd.DataFrame(metadata)
        df_metadata.to_excel(writer, sheet_name='Report Info', index=False)
    
    output.seek(0)
    return output


def export_evaluation_analysis_to_excel(
    evaluations: list[dict],
    company_name: str = "Siete CX"
) -> BytesIO:
    """
    Export evaluation analyses to Excel with multiple sheets
    
    Args:
        evaluations: List of evaluation dictionaries with analysis data
        company_name: Company name for the report
    
    Returns:
        BytesIO buffer containing Excel file
    """
    
    output = BytesIO()
    
    with pd.ExcelWriter(output, engine='openpyxl') as writer:
        # Main evaluations sheet
        eval_data = []
        for eval in evaluations:
            eval_data.append({
                'Evaluation ID': eval.get('id'),
                'Campaign': eval.get('campaign_name', ''),
                'Evaluator': eval.get('evaluator_name', ''),
                'Location': eval.get('location', ''),
                'Collaborator': eval.get('evaluated_collaborator', ''),
                'Status': eval.get('status', ''),
                'Created At': eval.get('created_at', ''),
            })
        
        df_evaluations = pd.DataFrame(eval_data)
        df_evaluations.to_excel(writer, sheet_name='Evaluations', index=False)
        
        # KPI scores sheet (from operative view)
        kpi_data = []
        for eval in evaluations:
            if 'analysis' in eval and 'operative_view' in eval['analysis']:
                try:
                    import json
                    operative = json.loads(eval['analysis']['operative_view'])
                    kpi_data.append({
                        'Evaluation ID': eval.get('id'),
                        'IOC Score': operative.get('IOC', {}).get('score', 0),
                        'IRD Score': operative.get('IRD', {}).get('score', 0),
                        'CES Score': operative.get('CES', {}).get('score', 0),
                        'Saludo': operative.get('Calidad', {}).get('saludo', False),
                        'Identificación': operative.get('Calidad', {}).get('identificacion', False),
                        'Ofrecimiento': operative.get('Calidad', {}).get('ofrecimiento', False),
                        'Cierre': operative.get('Calidad', {}).get('cierre', False),
                        'Valor Agregado': operative.get('Calidad', {}).get('valor_agregado', False),
                    })
                except:
                    continue
        
        if kpi_data:
            df_kpis = pd.DataFrame(kpi_data)
            df_kpis.to_excel(writer, sheet_name='KPI Scores', index=False)
        
        # Metadata
        metadata = {
            'Report': ['Evaluation Analysis Export'],
            'Company': [company_name],
            'Total Evaluations': [len(evaluations)],
            'Generated': [datetime.now().strftime('%Y-%m-%d %H:%M:%S')],
        }
        df_metadata = pd.DataFrame(metadata)
        df_metadata.to_excel(writer, sheet_name='Report Info', index=False)
    
    output.seek(0)
    return output


def generate_pdf_report(
    data: dict,
    company_name: str = "Siete CX",
    report_title: str = "Dashboard Report"
) -> BytesIO:
    """
    Generate PDF report from dashboard data
    
    Note: This requires additional dependencies (reportlab or weasyprint)
    For MVP, we'll create a simple HTML-to-PDF converter
    
    Args:
        data: Dashboard data dictionary
        company_name: Company name
        report_title: Report title
    
    Returns:
        BytesIO buffer containing PDF file
    """
    
    # For now, return a simple HTML representation
    # In production, use reportlab or weasyprint for proper PDF generation
    
    html_content = f"""
    <!DOCTYPE html>
    <html>
    <head>
        <title>{report_title}</title>
        <style>
            body {{ font-family: Arial, sans-serif; margin: 40px; }}
            h1 {{ color: #8b5cf6; }}
            h2 {{ color: #3b82f6; margin-top: 30px; }}
            table {{ border-collapse: collapse; width: 100%; margin-top: 20px; }}
            th, td {{ border: 1px solid #ddd; padding: 12px; text-align: left; }}
            th {{ background-color: #f3f4f6; font-weight: bold; }}
            .metric {{ display: inline-block; margin: 10px 20px; padding: 20px; background: #f9fafb; border-radius: 8px; }}
            .metric-value {{ font-size: 32px; font-weight: bold; color: #8b5cf6; }}
            .metric-label {{ font-size: 14px; color: #6b7280; }}
            .footer {{ margin-top: 50px; padding-top: 20px; border-top: 1px solid #ddd; font-size: 12px; color: #6b7280; }}
        </style>
    </head>
    <body>
        <h1>{report_title}</h1>
        <p><strong>Company:</strong> {company_name}</p>
        <p><strong>Generated:</strong> {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}</p>
        
        <h2>Key Metrics</h2>
        <div class="metrics">
    """
    
    # Add KPI metrics
    metrics_map = {
        'total_evaluations': 'Total Evaluations',
        'completed_evaluations': 'Completed',
        'pending_evaluations': 'Pending',
        'avg_nps': 'Average NPS',
    }
    
    for key, label in metrics_map.items():
        if key in data:
            value = data[key]
            if key == 'avg_nps' and isinstance(value, (int, float)):
                value = f"{value:.2f}"
            html_content += f"""
            <div class="metric">
                <div class="metric-value">{value}</div>
                <div class="metric-label">{label}</div>
            </div>
            """
    
    html_content += """
        </div>
        
        <h2>Additional Data</h2>
        <p>For detailed charts and graphs, please use the Excel export option.</p>
        
        <div class="footer">
            <p>Generated by Siete CX Platform</p>
        </div>
    </body>
    </html>
    """
    
    # Convert HTML to bytes
    output = BytesIO(html_content.encode('utf-8'))
    output.seek(0)
    
    return output


# Helper function to prepare dashboard data for export
def prepare_export_data(dashboard_response: dict, role: int) -> dict:
    """
    Transform dashboard API response into export-friendly format
    
    Args:
        dashboard_response: Response from GET /dashboard
        role: User role (0-3)
    
    Returns:
        Dictionary with normalized data for export
    """
    
    export_data = {}
    
    # Extract common metrics
    for key in [
        'total_companies', 'total_users', 'total_evaluations',
        'completed_evaluations', 'pending_evaluations', 'avg_nps',
        'active_campaigns'
    ]:
        if key in dashboard_response:
            export_data[key] = dashboard_response[key]
    
    # Add role-specific data
    if role == 0:  # Superadmin
        if 'companies_summary' in dashboard_response:
            export_data['companies_summary'] = dashboard_response['companies_summary']
    
    return export_data
