"""add new user columns

Revision ID: 224a6af40cce
Revises: 83d9617414a9
Create Date: 2025-06-05 12:09:53.478715

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "224a6af40cce"
down_revision: Union[str, None] = "83d9617414a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

civil_status_enum = sa.Enum(
    "SINGLE", "MARRIED", "DIVORCED", "WIDOWED", "SEPARATED", name="civilstatusenum"
)
inclusivity_enum = sa.Enum("LOW", "MEDIUM", "HIGH", name="socioeconomicenum")


def upgrade() -> None:
    op.execute(
        "CREATE TYPE civilstatusenum AS ENUM ('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED')"
    )
    op.execute("CREATE TYPE socioeconomicenum AS ENUM ('LOW', 'MEDIUM', 'HIGH')")
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("birthdate", sa.DateTime(), nullable=True))
    op.add_column(
        "users",
        sa.Column(
            "civil_status", civil_status_enum, nullable=True, server_default="SINGLE"
        ),
    )
    op.add_column(
        "users",
        sa.Column(
            "socioeconomic", inclusivity_enum, nullable=True, server_default="LOW"
        ),
    )
    op.add_column(
        "users",
        sa.Column("inclusivity", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.alter_column("users", "socioeconomic", server_default=None)
    op.alter_column("users", "civil_status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "inclusivity")
    op.drop_column("users", "socioeconomic")
    op.drop_column("users", "civil_status")
    op.drop_column("users", "birthdate")
    op.execute("DROP TYPE socioeconomicenum")
    op.execute("DROP TYPE civilstatusenum")
    # ### end Alembic commands ###
