"""Add analysis table

Revision ID: 308221bf950e
Revises: 5950a8028cef
Create Date: 2025-06-30 21:59:02.208725

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "308221bf950e"
down_revision: Union[str, None] = "5950a8028cef"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "evaluation_analysis",
        sa.Column("evaluation_id", sa.Integer(), nullable=True),
        sa.Column("analysis", sqlmodel.sql.sqltypes.AutoString(), nullable=False),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["evaluation_id"],
            ["evaluations.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.alter_column("videos", "status", existing_type=sa.VARCHAR(), nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column("videos", "status", existing_type=sa.VARCHAR(), nullable=True)
    op.drop_table("evaluation_analysis")
    # ### end Alembic commands ###
