"""refactor aspect and answers

Revision ID: 462cab603b3b
Revises: e3bce14109fc
Create Date: 2025-06-03 09:03:34.481995

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "462cab603b3b"
down_revision: Union[str, None] = "e3bce14109fc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

aspect_type_enum = sa.Enum("NUMBER", "BOOLEAN", name="aspecttypeenum")


def upgrade() -> None:
    # Crear el tipo ENUM en PostgreSQL si no existe
    op.execute("CREATE TYPE aspecttypeenum AS ENUM ('NUMBER', 'BOOLEAN')")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluation_answers", sa.Column("value_number", sa.Integer(), nullable=True)
    )
    op.add_column(
        "evaluation_answers", sa.Column("value_boolean", sa.Boolean(), nullable=True)
    )
    op.drop_column("evaluation_answers", "boolean_score")
    op.drop_column("evaluation_answers", "score")

    # Agregar la columna con valor por defecto
    op.add_column(
        "survey_aspects",
        sa.Column("type", aspect_type_enum, nullable=False, server_default="NUMBER"),
    )

    # Eliminar el valor por defecto después de la migración
    op.alter_column("survey_aspects", "type", server_default=None)

    op.drop_column("survey_aspects", "is_boolean")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "survey_aspects",
        sa.Column("is_boolean", sa.BOOLEAN(), autoincrement=False, nullable=False),
    )
    op.drop_column("survey_aspects", "type")
    op.add_column(
        "evaluation_answers",
        sa.Column("score", sa.INTEGER(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "evaluation_answers",
        sa.Column("boolean_score", sa.BOOLEAN(), autoincrement=False, nullable=True),
    )
    op.drop_column("evaluation_answers", "value_boolean")
    op.drop_column("evaluation_answers", "value_number")

    op.execute("DROP TYPE aspecttypeenum")

    # ### end Alembic commands ###
