"""Remove timezone on payment

Revision ID: 579905de4edd
Revises: 877eba3dc3df
Create Date: 2025-05-20 02:36:15.678399

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '579905de4edd'
down_revision: Union[str, None] = '877eba3dc3df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    op.alter_column('payments', 'valid_before',
               existing_type=postgresql.TIMESTAMP(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('payments', 'valid_before',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    op.alter_column('payments', 'date',
               existing_type=postgresql.TIMESTAMP(),
               nullable=False)
    # ### end Alembic commands ###
