"""add video status

Revision ID: 5950a8028cef
Revises: b1a2aa01b976
Create Date: 2025-06-16 13:34:19.082239

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "5950a8028cef"
down_revision: Union[str, None] = "b1a2aa01b976"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "videos", sa.Column("status", sqlmodel.sql.sqltypes.AutoString(), nullable=True)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "status")
    # ### end Alembic commands ###
