"""add campaign on evaluations

Revision ID: 83d9617414a9
Revises: d9bcd9ae2466
Create Date: 2025-06-05 09:53:32.658925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '83d9617414a9'
down_revision: Union[str, None] = 'd9bcd9ae2466'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('campaigns_id', sa.Integer(), nullable=True))
    op.drop_constraint('evaluations_company_id_fkey', 'evaluations', type_='foreignkey')
    op.create_foreign_key(None, 'evaluations', 'campaigns', ['campaigns_id'], ['id'])
    op.drop_column('evaluations', 'company_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('evaluations', sa.Column('company_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'evaluations', type_='foreignkey')
    op.create_foreign_key('evaluations_company_id_fkey', 'evaluations', 'companies', ['company_id'], ['id'])
    op.drop_column('evaluations', 'campaigns_id')
    # ### end Alembic commands ###
