"""Remove city to company

Revision ID: 877eba3dc3df
Revises: 88c781b130e9
Create Date: 2025-05-20 00:30:20.998188

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = '877eba3dc3df'
down_revision: Union[str, None] = '88c781b130e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('companies', 'city')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('companies', sa.Column('city', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
