"""added comment in notification

Revision ID: a09c305b48ac
Revises: 308221bf950e
Create Date: 2025-07-08 11:47:13.413132

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "a09c305b48ac"
down_revision: Union[str, None] = "308221bf950e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "notifications",
        sa.Column("comment", sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    )
    op.drop_column("videos", "status")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("videos", "status")
    op.drop_column("notifications", "comment")
    # ### end Alembic commands ###
