"""change survey models

Revision ID: a41ac71c8cd5
Revises: 7711c544895f
Create Date: 2025-05-28 17:03:52.849735

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'a41ac71c8cd5'
down_revision: Union[str, None] = '7711c544895f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('survey_forms',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('survey_answers', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('survey_answers', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('survey_answers', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.drop_constraint('survey_answers_survey_id_fkey', 'survey_answers', type_='foreignkey')
    op.drop_constraint('survey_answers_aspect_id_fkey', 'survey_answers', type_='foreignkey')
    op.drop_column('survey_answers', 'score')
    op.drop_column('survey_answers', 'comment')
    op.drop_column('survey_answers', 'survey_id')
    op.drop_column('survey_answers', 'aspect_id')
    op.add_column('survey_aspects', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('survey_aspects', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('survey_aspects', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.add_column('survey_sections', sa.Column('form_id', sa.Integer(), nullable=True))
    op.add_column('survey_sections', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('survey_sections', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('survey_sections', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'survey_sections', 'survey_forms', ['form_id'], ['id'])
    op.add_column('surveys', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('surveys', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.add_column('surveys', sa.Column('deleted_at', sa.DateTime(), nullable=True))
    op.create_foreign_key(None, 'surveys', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'surveys', type_='foreignkey')
    op.drop_column('surveys', 'deleted_at')
    op.drop_column('surveys', 'updated_at')
    op.drop_column('surveys', 'created_at')
    op.drop_column('surveys', 'company_id')
    op.drop_constraint(None, 'survey_sections', type_='foreignkey')
    op.drop_column('survey_sections', 'deleted_at')
    op.drop_column('survey_sections', 'updated_at')
    op.drop_column('survey_sections', 'created_at')
    op.drop_column('survey_sections', 'form_id')
    op.drop_column('survey_aspects', 'deleted_at')
    op.drop_column('survey_aspects', 'updated_at')
    op.drop_column('survey_aspects', 'created_at')
    op.add_column('survey_answers', sa.Column('aspect_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('survey_answers', sa.Column('survey_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('survey_answers', sa.Column('comment', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('survey_answers', sa.Column('score', sa.INTEGER(), autoincrement=False, nullable=False))
    op.create_foreign_key('survey_answers_aspect_id_fkey', 'survey_answers', 'survey_aspects', ['aspect_id'], ['id'])
    op.create_foreign_key('survey_answers_survey_id_fkey', 'survey_answers', 'surveys', ['survey_id'], ['id'])
    op.drop_column('survey_answers', 'deleted_at')
    op.drop_column('survey_answers', 'updated_at')
    op.drop_column('survey_answers', 'created_at')
    op.drop_table('survey_forms')
    # ### end Alembic commands ###
