"""add widgets and onboarding tables

Revision ID: c9082924ebb0
Revises: bb9c6359b94f
Create Date: 2025-11-12 11:23:09.511792

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'c9082924ebb0'
down_revision: Union[str, None] = 'bb9c6359b94f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_goals_progress',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('goal_evaluator', sa.Integer(), nullable=False),
    sa.Column('goal_complete', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', 'evaluator_id')
    )
    op.create_table('company_users_evaluations',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('gerentes', sa.Integer(), nullable=True),
    sa.Column('evaluadores', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_aprobadas', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_rechazadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('manager_summary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('zonas_asignadas', sa.Integer(), nullable=False),
    sa.Column('evaluadores_asignados', sa.Integer(), nullable=False),
    sa.Column('active_campaigns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('superadmin_summary',
    sa.Column('superadmin_id', sa.Integer(), nullable=False),
    sa.Column('total_empresas', sa.Integer(), nullable=False),
    sa.Column('empresas_vigentes', sa.Integer(), nullable=False),
    sa.Column('empresas_caducadas', sa.Integer(), nullable=False),
    sa.Column('usuarios_totales', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('superadmin_id')
    )
    op.create_table('user_evaluation_summary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rechazadas', sa.Integer(), nullable=True),
    sa.Column('aprobadas', sa.Integer(), nullable=True),
    sa.Column('ediciones_pendientes', sa.Integer(), nullable=True),
    sa.Column('enviadas', sa.Integer(), nullable=True),
    sa.Column('actualizadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.alter_column('campaigns', 'goal',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('campaigns', 'goal',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_table('user_evaluation_summary')
    op.drop_table('superadmin_summary')
    op.drop_table('manager_summary')
    op.drop_table('company_users_evaluations')
    op.drop_table('campaign_goals_progress')
    # ### end Alembic commands ###
