"""add status in evaluations

Revision ID: d9bcd9ae2466
Revises: 462cab603b3b
Create Date: 2025-06-05 09:27:25.135890

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = "d9bcd9ae2466"
down_revision: Union[str, None] = "462cab603b3b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

status_enum = sa.Enum("SEND", "UPDATED", "APROVED", "REJECTED", name="statusenum")


def upgrade() -> None:
    op.execute(
        "CREATE TYPE statusenum AS ENUM ('SEND', 'UPDATED', 'APROVED', 'REJECTED')"
    )
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "evaluations",
        sa.Column("status", status_enum, nullable=False, server_default="SEND"),
    )
    op.alter_column("evaluations", "status", server_default=None)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("evaluations", "status")
    op.execute("DROP TYPE statusenum")
    # ### end Alembic commands ###
