"""remove status form video table

Revision ID: ddbcc7fdc927
Revises: 864f764afeab
Create Date: 2025-07-10 12:39:20.352975

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'ddbcc7fdc927'
down_revision: Union[str, None] = '864f764afeab'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('videos', 'status')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('videos', sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
