"""add campaign

Revision ID: f6aee2a67e9c
Revises: a41ac71c8cd5
Create Date: 2025-05-29 14:49:31.934656

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'f6aee2a67e9c'
down_revision: Union[str, None] = 'a41ac71c8cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Enum('presencial', 'telefonico', 'online', name='channeltype'), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('survey_answers', sa.Column('survey_id', sa.Integer(), nullable=True))
    op.add_column('survey_answers', sa.Column('aspect_id', sa.Integer(), nullable=True))
    op.add_column('survey_answers', sa.Column('score', sa.Integer(), nullable=False))
    op.add_column('survey_answers', sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.create_foreign_key(None, 'survey_answers', 'survey_aspects', ['aspect_id'], ['id'])
    op.create_foreign_key(None, 'survey_answers', 'surveys', ['survey_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_answers', type_='foreignkey')
    op.drop_constraint(None, 'survey_answers', type_='foreignkey')
    op.drop_column('survey_answers', 'comment')
    op.drop_column('survey_answers', 'score')
    op.drop_column('survey_answers', 'aspect_id')
    op.drop_column('survey_answers', 'survey_id')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
