"""add company integration fields

Revision ID: f7236061f41c
Revises: f10d72303278
Create Date: 2025-12-22 20:34:00.675041

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'f7236061f41c'
down_revision: Union[str, None] = 'f10d72303278'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('company_users_evaluations',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('gerentes', sa.Integer(), nullable=True),
    sa.Column('evaluadores', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_aprobadas', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_rechazadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.alter_column('alert_thresholds', 'alert_severity',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_thresholds', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('alert_thresholds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('alert_thresholds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.add_column('companies', sa.Column('slack_webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('companies', sa.Column('webhook_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('companies', sa.Column('webhook_secret', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.drop_index(op.f('ix_company_themes_company_id'), table_name='company_themes')
    op.alter_column('dashboard_configs', 'layout_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('dashboard_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('dashboard_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('dashboard_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.add_column('evaluation_analysis', sa.Column('sentiment', sa.JSON(), nullable=True))
    op.alter_column('evaluation_tags', 'auto_tagged',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('evaluation_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('insights', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('insights', 'metrics',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('insights', 'suggested_actions',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('insights', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insights', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('insights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_insights_company_id'), table_name='insights')
    op.drop_index(op.f('ix_insights_deleted_at'), table_name='insights')
    op.alter_column('prompts', 'name',
               existing_type=sa.VARCHAR(length=100),
               type_=sqlmodel.sql.sqltypes.AutoString(length=255),
               existing_nullable=False)
    op.alter_column('prompts', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.alter_column('prompts', 'template',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('prompts', 'variables',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('prompts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('prompts', 'version',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('prompts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.drop_index(op.f('ix_prompts_category'), table_name='prompts')
    op.alter_column('tags', 'category',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('tags', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('trends', 'trend_metadata',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('trends', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('widget_definitions', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=False)
    op.alter_column('widget_definitions', 'default_config',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.alter_column('widget_definitions', 'available_for_roles',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               nullable=True)
    op.alter_column('widget_definitions', 'category',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('widget_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('widget_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=None,
               nullable=True)
    op.alter_column('widget_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('widget_definitions', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('widget_definitions', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('widget_definitions', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('widget_definitions', 'category',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=False)
    op.alter_column('widget_definitions', 'available_for_roles',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('widget_definitions', 'default_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('widget_definitions', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('trends', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('trends', 'trend_metadata',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('tags', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('tags', 'color',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'#6b7280'::character varying"),
               existing_nullable=False)
    op.alter_column('tags', 'category',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'general'::character varying"),
               existing_nullable=False)
    op.create_index(op.f('ix_prompts_category'), 'prompts', ['category'], unique=False)
    op.alter_column('prompts', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('prompts', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('prompts', 'company_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('prompts', 'version',
               existing_type=sa.INTEGER(),
               server_default=sa.text('1'),
               existing_nullable=False)
    op.alter_column('prompts', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('prompts', 'variables',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.alter_column('prompts', 'template',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('prompts', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('prompts', 'name',
               existing_type=sqlmodel.sql.sqltypes.AutoString(length=255),
               type_=sa.VARCHAR(length=100),
               existing_nullable=False)
    op.create_index(op.f('ix_insights_deleted_at'), 'insights', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_insights_company_id'), 'insights', ['company_id'], unique=False)
    op.alter_column('insights', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('insights', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('insights', 'is_resolved',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('insights', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('insights', 'suggested_actions',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insights', 'metrics',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    op.alter_column('insights', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('evaluation_tags', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('evaluation_tags', 'auto_tagged',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.drop_column('evaluation_analysis', 'sentiment')
    op.alter_column('dashboard_configs', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('dashboard_configs', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('dashboard_configs', 'is_default',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('dashboard_configs', 'layout_config',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    op.create_index(op.f('ix_company_themes_company_id'), 'company_themes', ['company_id'], unique=False)
    op.drop_column('companies', 'webhook_secret')
    op.drop_column('companies', 'webhook_url')
    op.drop_column('companies', 'slack_webhook_url')
    op.alter_column('alert_thresholds', 'updated_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('alert_thresholds', 'created_at',
               existing_type=postgresql.TIMESTAMP(),
               server_default=sa.text('now()'),
               nullable=False)
    op.alter_column('alert_thresholds', 'is_active',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'),
               existing_nullable=False)
    op.alter_column('alert_thresholds', 'alert_severity',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'medium'::character varying"),
               existing_nullable=False)
    op.drop_table('company_users_evaluations')
    # ### end Alembic commands ###
