"""crear tabla widgets completa

Revision ID: fd400e2f4e52
Revises: 3fdbf1a24324
Create Date: 2025-11-13 11:43:06.423580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel.sql.sqltypes


# revision identifiers, used by Alembic.
revision: str = 'fd400e2f4e52'
down_revision: Union[str, None] = '3fdbf1a24324'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign_goals_progress',
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('campaign_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('goal_evaluator', sa.Integer(), nullable=False),
    sa.Column('goal_complete', sa.Integer(), nullable=False),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('campaign_id', 'evaluator_id')
    )
    op.create_table('companies',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('state', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_users_evaluations',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('gerentes', sa.Integer(), nullable=True),
    sa.Column('evaluadores', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_aprobadas', sa.Integer(), nullable=True),
    sa.Column('evaluaciones_rechazadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('company_id')
    )
    op.create_table('manager_summary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('zonas_asignadas', sa.Integer(), nullable=False),
    sa.Column('evaluadores_asignados', sa.Integer(), nullable=False),
    sa.Column('active_campaigns', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('superadmin_summary',
    sa.Column('superadmin_id', sa.Integer(), nullable=False),
    sa.Column('total_empresas', sa.Integer(), nullable=False),
    sa.Column('empresas_vigentes', sa.Integer(), nullable=False),
    sa.Column('empresas_caducadas', sa.Integer(), nullable=False),
    sa.Column('usuarios_totales', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('superadmin_id')
    )
    op.create_table('user_evaluation_summary',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('rechazadas', sa.Integer(), nullable=True),
    sa.Column('aprobadas', sa.Integer(), nullable=True),
    sa.Column('ediciones_pendientes', sa.Integer(), nullable=True),
    sa.Column('enviadas', sa.Integer(), nullable=True),
    sa.Column('actualizadas', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('videos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('zones',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('value', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('company_themes',
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('company_logo_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_favicon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('company_name_override', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('primary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('secondary_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('accent_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('success_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('warning_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('error_color', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('font_family_primary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('font_family_secondary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('sidebar_background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('header_background', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('custom_css', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('features_config', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('company_id')
    )
    op.create_table('payments',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('valid_before', sa.DateTime(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_forms',
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('role', sa.Integer(), nullable=False),
    sa.Column('first_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('last_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('gender', sa.Enum('MALE', 'FEMALE', 'OTHER', name='genderenum'), nullable=False),
    sa.Column('birthdate', sa.DateTime(), nullable=True),
    sa.Column('civil_status', sa.Enum('SINGLE', 'MARRIED', 'DIVORCED', 'WIDOWED', 'SEPARATED', name='civilstatusenum'), nullable=True),
    sa.Column('socioeconomic', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='socioeconomicenum'), nullable=True),
    sa.Column('inclusivity', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('widgets',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=True),
    sa.Column('type', sa.Enum('METRIC_CARD', 'LINE_CHART', 'BAR_CHART', 'PIE_CHART', 'TABLE', 'MAP', 'HEATMAP', 'LEADERBOARD', 'RECENT_ACTIVITY', 'ALERTS', name='widgettype'), nullable=False),
    sa.Column('role_restriction', sa.Integer(), nullable=True),
    sa.Column('config', sa.JSON(), nullable=True),
    sa.Column('default_position', sa.JSON(), nullable=True),
    sa.Column('data_source', sa.Enum('EVALUATIONS', 'CAMPAIGNS', 'USERS', 'ZONES', 'CUSTOM', name='datasource'), nullable=False),
    sa.Column('query_params', sa.JSON(), nullable=True),
    sa.Column('is_public', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaigns',
    sa.Column('company_id', sa.Integer(), nullable=True),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('date_start', sa.DateTime(), nullable=False),
    sa.Column('date_end', sa.DateTime(), nullable=False),
    sa.Column('channel', sa.Enum('presencial', 'telefonico', 'online', name='channeltype'), nullable=False),
    sa.Column('survey_id', sa.Integer(), nullable=True),
    sa.Column('notes', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['company_id'], ['companies.id'], ),
    sa.ForeignKeyConstraint(['survey_id'], ['survey_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('onboarding_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('steps_completed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('tours_completed', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('total_steps', sa.Integer(), nullable=False),
    sa.Column('progress_percentage', sa.Integer(), nullable=False),
    sa.Column('is_completed', sa.Boolean(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('skipped', sa.Boolean(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('last_interaction', sa.DateTime(), nullable=True),
    sa.Column('days_to_complete', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_onboarding_status_user_id'), 'onboarding_status', ['user_id'], unique=True)
    op.create_table('survey_sections',
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('maximum_score', sa.Integer(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('form_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['form_id'], ['survey_forms.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_dashboard_widgets',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('widget_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.JSON(), nullable=True),
    sa.Column('custom_config', sa.JSON(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=False),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['widget_id'], ['widgets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_zones',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('zone_id', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_goals_evaluators',
    sa.Column('evaluator_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('goal', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['evaluator_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_users',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_zones',
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('zone_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['zone_id'], ['zones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluations',
    sa.Column('campaigns_id', sa.Integer(), nullable=True),
    sa.Column('video_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('location', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('evaluated_collaborator', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('status', sa.Enum('SEND', 'EDIT', 'UPDATED', 'APROVED', 'REJECTED', name='statusenum'), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaigns_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['video_id'], ['videos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('survey_aspects',
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('NUMBER', 'BOOLEAN', name='aspecttypeenum'), nullable=False),
    sa.Column('maximum_score', sa.Integer(), nullable=True),
    sa.Column('section_id', sa.Integer(), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['section_id'], ['survey_sections.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_analysis',
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('analysis', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('executive_view', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('operative_view', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_answers',
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('aspect_id', sa.Integer(), nullable=True),
    sa.Column('value_number', sa.Integer(), nullable=True),
    sa.Column('value_boolean', sa.Boolean(), nullable=True),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['aspect_id'], ['survey_aspects.id'], ),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notifications',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('evaluation_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.Enum('SEND', 'EDIT', 'UPDATED', 'APROVED', 'REJECTED', name='statusenum'), nullable=False),
    sa.Column('read', sa.Boolean(), nullable=False),
    sa.Column('comment', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['evaluation_id'], ['evaluations.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_table('evaluation_answers')
    op.drop_table('evaluation_analysis')
    op.drop_table('survey_aspects')
    op.drop_table('evaluations')
    op.drop_table('campaign_zones')
    op.drop_table('campaign_users')
    op.drop_table('campaign_goals_evaluators')
    op.drop_table('user_zones')
    op.drop_table('user_dashboard_widgets')
    op.drop_table('survey_sections')
    op.drop_index(op.f('ix_onboarding_status_user_id'), table_name='onboarding_status')
    op.drop_table('onboarding_status')
    op.drop_table('campaigns')
    op.drop_table('widgets')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('survey_forms')
    op.drop_table('payments')
    op.drop_table('company_themes')
    op.drop_table('zones')
    op.drop_table('videos')
    op.drop_table('user_evaluation_summary')
    op.drop_table('superadmin_summary')
    op.drop_table('manager_summary')
    op.drop_table('company_users_evaluations')
    op.drop_table('companies')
    op.drop_table('campaign_goals_progress')
    # ### end Alembic commands ###
