#!/bin/bash
echo "==================================="
echo "Railway Logs Retrieval Guide"
echo "==================================="
echo ""
echo "Run these commands on your local machine:"
echo ""
echo "1. Install Railway CLI:"
echo "   npm install -g @railway/cli"
echo ""
echo "2. Login:"
echo "   railway login"
echo ""
echo "3. Link to your project:"
echo "   railway link"
echo ""
echo "4. View build logs:"
echo "   railway logs --deployment"
echo ""
echo "5. Copy ALL output and share with me"
echo ""
