#!/bin/bash

echo "=========================================="
echo "  EJECUTAR MIGRACIONES EN RAILWAY"
echo "=========================================="
echo ""
echo "OPCIÓN 1: Usando Railway CLI"
echo ""
echo "1. Instala Railway CLI si no lo tienes:"
echo "   npm install -g @railway/cli"
echo ""
echo "2. Login a Railway:"
echo "   railway login"
echo ""
echo "3. Vincula tu proyecto:"
echo "   railway link"
echo ""
echo "4. Ejecuta las migraciones:"
echo "   railway run alembic upgrade head"
echo ""
echo "=========================================="
echo ""
echo "OPCIÓN 2: Desde Railway Dashboard"
echo ""
echo "1. Ve a tu servicio en Railway"
echo "2. Click en pestaña 'Settings'"
echo "3. Busca 'Custom Start Command'"
echo "4. Temporalmente cambia a:"
echo "   alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo "5. Guarda y espera que redeploy"
echo "6. Una vez completado, REMUEVE el 'alembic upgrade head &&'"
echo "7. Deja solo: uvicorn app.main:app --host 0.0.0.0 --port \$PORT"
echo ""
echo "=========================================="
echo ""
echo "VERIFICACIÓN:"
echo "Las migraciones crean estas tablas:"
echo "  - users"
echo "  - companies"
echo "  - campaigns"
echo "  - evaluations"
echo "  - dashboard_configs"
echo "  - widget_definitions"
echo "  - insights"
echo "  - trends"
echo "  - ai_tags"
echo "  - prompt_managers"
echo "  - company_themes"
echo "  - notifications"
echo "  - y más..."
echo ""
echo "Puedes verificar en Railway → PostgreSQL → Data"
echo ""
