from .auth_router import router as auth_router
from .campaign_assigment_users import router as campaign_assigment_users_router
from .campaign_assigment_zones import router as campaign_assigment_zones_router
from .campaign_assignment import router as campaign_assignment_router
from .campaign_goals_evaluator import router as campaign_goals_evaluator_router
from .campaign_goals_progress import router as campaign_goals_progress_router
from .campaign import router as campaign_router
from .cloudflare import router as cloudflare_router
from .cloudflare_webhook import router as cloudflare_webhook_router
from .company import router as company_router
from .dashboard import router as dashboard_router
from .evaluation_analysis import router as evaluation_analysis_router
from .evaluation_event import router as evaluation_event_router
from .evaluation import router as evaluation_router
from .notification import router as notification_router
from .survey import router as survey_router
from .user import router as user_router
from .payment import router as payment_router
from .processing_job import router as processing_job_router
from .user_zone import router as user_zone_router
from .zone import router as zone_router
from .transcript_segment import router as transcript_segment_router
from .executive import router as executive_router
