from fastapi import APIRouter
from app.routes import (
    action_plan_router,
    audit_router,
    auth_router,
    branch_router,
    gap_analysis_router,
    interaction_phase_router,
    campaign_assigment_users_router,
    campaign_assigment_zones_router,
    campaign_assignment_router,
    campaign_goals_evaluator_router,
    campaign_goals_progress_router,
    campaign_router,
    cloudflare_router,
    cloudflare_webhook_router,
    company_router,
    dashboard_router,
    evaluation_analysis_router,
    evaluation_event_router,
    evaluation_router,
    notification_router,
    survey_router,
    user_router,
    payment_router,
    processing_job_router,
    user_zone_router,
    zone_router,
    transcript_segment_router,
    executive_router,
    clips_router,
    intelligence_router,
    prompts_router,
    quality_framework_router,
    ins_router,
    entitlements_router,
    end_clients_router,
    field_router,
)


api_router = APIRouter()

api_router.include_router(action_plan_router)
api_router.include_router(audit_router)
api_router.include_router(auth_router)
api_router.include_router(branch_router)
api_router.include_router(gap_analysis_router)
api_router.include_router(interaction_phase_router)
api_router.include_router(user_router)
api_router.include_router(company_router)
api_router.include_router(payment_router)
api_router.include_router(processing_job_router)
api_router.include_router(zone_router)
api_router.include_router(user_zone_router)
api_router.include_router(survey_router)
api_router.include_router(campaign_router)
api_router.include_router(campaign_assignment_router)
api_router.include_router(campaign_assigment_users_router)
api_router.include_router(campaign_assigment_zones_router)
api_router.include_router(evaluation_router)
api_router.include_router(notification_router)
api_router.include_router(dashboard_router)
api_router.include_router(cloudflare_router)
api_router.include_router(cloudflare_webhook_router)
api_router.include_router(evaluation_analysis_router)
api_router.include_router(evaluation_event_router)
api_router.include_router(campaign_goals_evaluator_router)
api_router.include_router(campaign_goals_progress_router)
api_router.include_router(transcript_segment_router)
api_router.include_router(executive_router)
api_router.include_router(clips_router)
api_router.include_router(intelligence_router)
api_router.include_router(prompts_router)
api_router.include_router(quality_framework_router)
api_router.include_router(ins_router)
api_router.include_router(entitlements_router)
api_router.include_router(end_clients_router)
api_router.include_router(field_router)
