INSERT INTO zones (name, value, country)
VALUES 
('Azua', 2, 'DO'),
('Baoruco', 3, 'DO'),
('Barahona', 4, 'DO'),
('Dajabón', 5, 'DO'),
('Distrito Nacional', 1, 'DO'),
('Duarte', 6, 'DO'),
('El Seibo', 8, 'DO'),
('Espaillat', 9, 'DO'),
('Hato Mayor', 30, 'DO'),
('Hermanas Mirabal', 19, 'DO'),
('Independencia', 10, 'DO'),
('La Altagracia', 11, 'DO'),
('La Romana', 12, 'DO'),
('La Vega', 13, 'DO'),
('María Trinidad Sánchez', 14, 'DO'),
('Monseñor Nouel', 28, 'DO'),
('Monte Cristi', 15, 'DO'),
('Monte Plata', 29, 'DO'),
('Pedernales', 16, 'DO'),
('Peravia', 17, 'DO'),
('Puerto Plata', 18, 'DO'),
('Samaná', 20, 'DO'),
('San Cristóbal', 21, 'DO'),
('San José de Ocoa', 31, 'DO'),
('San Juan', 22, 'DO'),
('San Pedro de Macorís', 23, 'DO'),
('Santiago', 25, 'DO'),
('Santiago Rodríguez', 26, 'DO'),
('Santo Domingo', 32, 'DO'),
('Sánchez Ramírez', 24, 'DO'),
('Valverde', 27, 'DO');
