from datetime import datetime
from sqlmodel import Column, DateTime, Field, Relationship, SQLModel, func
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from app.models.company_model import Company
    from app.models.evaluation_model import Evaluation


class InsightBase(SQLModel):
    """Base model for automated insights"""
    company_id: int = Field(foreign_key="companies.id")
    evaluation_id: int | None = Field(default=None, foreign_key="evaluations.id", nullable=True)
    insight_type: str = Field(
        description="Type: nps_alert, ird_alert, ces_alert, quality_issue, opportunity, trend"
    )
    severity: str = Field(
        default="medium",
        description="Severity: low, medium, high, critical"
    )
    title: str = Field(max_length=200, description="Brief insight title")
    description: str = Field(description="Detailed insight description")
    metrics: dict | None = Field(
        default=None,
        sa_column_kwargs={"type_": "JSONB"},
        description="Related metrics (IOC, IRD, CES, NPS, etc.)"
    )
    suggested_actions: list | None = Field(
        default=None,
        sa_column_kwargs={"type_": "JSONB"},
        description="List of suggested actions"
    )
    is_read: bool = Field(default=False, description="Whether insight has been viewed")
    is_resolved: bool = Field(default=False, description="Whether issue has been resolved")


class InsightCreate(InsightBase):
    """Schema for creating an insight"""
    pass


class InsightUpdate(SQLModel):
    """Schema for updating an insight"""
    is_read: bool | None = None
    is_resolved: bool | None = None


class Insight(InsightBase, table=True):
    """Database table for insights"""
    __tablename__ = "insights"
    
    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(sa_column=Column(DateTime, default=func.now()))
    updated_at: datetime = Field(
        sa_column=Column(DateTime, default=func.now(), onupdate=func.now())
    )
    deleted_at: datetime | None = Field(default=None)
    
    company: "Company" = Relationship(sa_relationship_kwargs={"lazy": "noload"})
    evaluation: "Evaluation" = Relationship(sa_relationship_kwargs={"lazy": "noload"})


class InsightPublic(InsightBase):
    """Public schema for insight"""
    id: int
    created_at: datetime
    updated_at: datetime


class InsightsPublic(SQLModel):
    """Paginated response for insights"""
    data: list[InsightPublic]
    total: int


# Tags System
class TagBase(SQLModel):
    """Base model for evaluation tags"""
    name: str = Field(max_length=50, description="Tag name")
    category: str = Field(
        default="general",
        description="Category: quality, issue, opportunity, compliance, performance"
    )
    color: str = Field(default="#6b7280", description="Hex color for UI display")
    company_id: int | None = Field(default=None, foreign_key="companies.id", nullable=True)


class Tag(TagBase, table=True):
    """Database table for tags"""
    __tablename__ = "tags"
    
    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(sa_column=Column(DateTime, default=func.now()))
    is_active: bool = Field(default=True)


class TagPublic(TagBase):
    """Public schema for tag"""
    id: int
    is_active: bool


class TagsPublic(SQLModel):
    """List response for tags"""
    data: list[TagPublic]
    total: int


# Evaluation Tags (many-to-many relationship)
class EvaluationTagBase(SQLModel):
    """Base model for evaluation-tag association"""
    evaluation_id: int = Field(foreign_key="evaluations.id")
    tag_id: int = Field(foreign_key="tags.id")
    auto_tagged: bool = Field(
        default=True,
        description="Whether tag was auto-generated by AI or manually added"
    )


class EvaluationTag(EvaluationTagBase, table=True):
    """Database table for evaluation tags"""
    __tablename__ = "evaluation_tags"
    
    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(sa_column=Column(DateTime, default=func.now()))


class EvaluationTagPublic(EvaluationTagBase):
    """Public schema for evaluation tag"""
    id: int
    tag: TagPublic | None = None


# Alert Thresholds Configuration
class AlertThresholdBase(SQLModel):
    """Base model for alert threshold configuration"""
    company_id: int = Field(foreign_key="companies.id")
    metric_name: str = Field(
        description="Metric: IOC, IRD, CES, NPS, quality_score, etc."
    )
    condition: str = Field(
        description="Condition: greater_than, less_than, equals, between"
    )
    threshold_value: float = Field(description="Threshold value for alert")
    threshold_value_max: float | None = Field(
        default=None,
        description="Max value for 'between' condition"
    )
    alert_severity: str = Field(
        default="medium",
        description="Severity: low, medium, high, critical"
    )
    is_active: bool = Field(default=True, description="Whether this threshold is active")


class AlertThresholdCreate(AlertThresholdBase):
    """Schema for creating alert threshold"""
    pass


class AlertThresholdUpdate(SQLModel):
    """Schema for updating alert threshold"""
    threshold_value: float | None = None
    threshold_value_max: float | None = None
    alert_severity: str | None = None
    is_active: bool | None = None


class AlertThreshold(AlertThresholdBase, table=True):
    """Database table for alert thresholds"""
    __tablename__ = "alert_thresholds"
    
    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(sa_column=Column(DateTime, default=func.now()))
    updated_at: datetime = Field(
        sa_column=Column(DateTime, default=func.now(), onupdate=func.now())
    )
    
    company: "Company" = Relationship(sa_relationship_kwargs={"lazy": "noload"})


class AlertThresholdPublic(AlertThresholdBase):
    """Public schema for alert threshold"""
    id: int
    created_at: datetime


class AlertThresholdsPublic(SQLModel):
    """List response for alert thresholds"""
    data: list[AlertThresholdPublic]
    total: int


# Trend Tracking
class TrendBase(SQLModel):
    """Base model for trend tracking"""
    company_id: int = Field(foreign_key="companies.id")
    metric_name: str = Field(description="Metric being tracked")
    period: str = Field(
        description="Period: daily, weekly, monthly"
    )
    start_date: datetime = Field(description="Period start date")
    end_date: datetime = Field(description="Period end date")
    average_value: float = Field(description="Average value for the period")
    min_value: float = Field(description="Minimum value")
    max_value: float = Field(description="Maximum value")
    sample_count: int = Field(description="Number of samples in period")
    trend_direction: str | None = Field(
        default=None,
        description="Trend: improving, declining, stable"
    )
    metadata: dict | None = Field(
        default=None,
        sa_column_kwargs={"type_": "JSONB"},
        description="Additional trend data"
    )


class Trend(TrendBase, table=True):
    """Database table for trends"""
    __tablename__ = "trends"
    
    id: int | None = Field(default=None, primary_key=True)
    created_at: datetime = Field(sa_column=Column(DateTime, default=func.now()))
    
    company: "Company" = Relationship(sa_relationship_kwargs={"lazy": "noload"})


class TrendPublic(TrendBase):
    """Public schema for trend"""
    id: int
    created_at: datetime


class TrendsPublic(SQLModel):
    """List response for trends"""
    data: list[TrendPublic]
    total: int
