import importlib
import inspect
from pathlib import Path

HEADER = '''"""
App Models - Auto-generated from shared.models
This file is generated by tools/generate_app_models_init.py
Do not edit by hand.
"""
'''

BASE_IMPORT = "from sqlmodel import SQLModel\n\n"
SHARED_MODELS_DIR = Path("shared/models")


def is_db_model(obj):
    # Import aquí para evitar problemas de orden
    from sqlmodel import SQLModel

    if not inspect.isclass(obj):
        return False
    if not issubclass(obj, SQLModel):
        return False
    if obj is SQLModel:
        return False

    # Tabla si tiene __table__ o __tablename__
    has_table = getattr(obj, "__table__", None) is not None
    has_tablename = hasattr(obj, "__tablename__")
    return has_table or has_tablename


def main():
    models: list[tuple[str, str]] = []  # (module_name, class_name)

    for path in SHARED_MODELS_DIR.glob("*_model.py"):
        module_name = path.stem  # e.g. "user_model"
        import_path = f"shared.models.{module_name}"
        module = importlib.import_module(import_path)

        for name, obj in inspect.getmembers(module):
            if is_db_model(obj):
                models.append((module_name, name))

    # Ordenar para salida determinista
    models.sort()

    lines: list[str] = [HEADER, BASE_IMPORT]

    current_module = None
    for module_name, class_name in models:
        if module_name != current_module:
            if current_module is not None:
                lines.append("")  # línea en blanco entre módulos
            current_module = module_name
            lines.append(f"from shared.models.{module_name} import {class_name}")
        else:
            last = lines.pop()
            last = last + f", {class_name}"
            lines.append(last)

    lines.append("")
    lines.append("__all__ = [")
    for _, class_name in models:
        lines.append(f'    "{class_name}",')
    lines.append("]")

    out_path = Path("app/models/__init__.py")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text("\n".join(lines), encoding="utf-8")

    print(f"Generated {out_path} with {len(models)} DB models.")


if __name__ == "__main__":
    main()
